version: '3.1'
services:
  certbot:
    image: ubuntu:16.04
    container_name: certbot
    tty: true
    stdin_open: true
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
