# This template is using exists vpc network. two public subnet and two private subnet
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-example
  region: ap-northeast-1

vpc:
  id: ""  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      ap-northeast-1a:
        id: ""
        cidr: "10.0.10.0/24" # (optional, must match CIDR used by the given subnet)

      ap-northeast-1c:
        id: ""
        cidr: "10.0.110.0/24"  # (optional, must match CIDR used by the given subnet)
    private:
       ap-northeast-1a:
         id: ""
         cidr: "10.0.20.0/24"
       ap-northeast-1c:
         id: ""
         cidr: "10.0.120.0/24"

nodeGroups:
  - name: prod-ng1-private
    minSize: 2
    desiredCapacity: 2
    maxSize: 5
    instancesDistribution: # using spot
      maxPrice: 0.017
      instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
      onDemandBaseCapacity: 1
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 3
    ssh: # import public key from file
      publicKeyPath: ~/.ssh/yourkey.pem
    availabilityZones: ["ap-northeast-1a", "ap-northeast-1c"]
    volumeSize: 20
    privateNetworking: true
